// import type { Metadata } from 'next';
import { Saira, Roboto_Mono } from 'next/font/google';
import '../styles/global.css';
import { ThemeProvider } from '../components/theme-provider';

const saira = Saira({
  variable: '--font-saira',
  subsets: ['latin'],
  weight: ['300', '400', '500'],
});

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin'],
  weight: ['300', '400', '500'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${saira.variable} ${robotoMono.variable}`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
