// import type { Metadata } from 'next';
import { Saira, Roboto_Mono } from 'next/font/google';
import '../styles/global.css';
import { ThemeProvider } from '../components/theme-provider';
import { StoreProvider } from '@/store/utils/contextProvider';
// import { ModalRoot } from '@/components/modals/ModalRoot';
import ClientWrapper from '@/components/ClientWrapper';

const saira = Saira({
  variable: '--font-saira',
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
});

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin'],
  weight: ['300', '400', '500'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning className='h-screen overflow-auto'>
      <body
        className={`${saira.variable} ${robotoMono.variable} px-10 pt-7 h-full overflow-auto`}
      >
        <StoreProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='light' // TODO: change to system
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <ClientWrapper />
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
